- name: Rollback wordpress sur web
  hosts: web
  become: yes
  vars_files:
    - vars/default.yml
  #  - "{{ ansible_os_family }}.yml"

  tasks:
    #- name: Include OS-Specific
    #  include_vars: "{{ ansible_os_family }}.yml"

    - name: Suppression Apache
      package:
        name: httpd # "{{ apache_pkg }}"
        state: absent

    - name: Delete Apache Document Root
      file:
        path: "/var/www/{{ http_host }}"
        state: absent
    
    - name: Rollback Apache VirtualHost
      file:
        path: "/etc/httpd/conf.d/{{ http_conf }}"
        state: absent

# MySQL Configuration
    - name: Delete MySQL Packages
      package: 
        name: "{{ item }}"
        update_cache: yes 
        state: absent
      loop: [ 'mysql-server', 'php-mysqlnd', 'python3-PyMySQL' ]
 

 
 