---
#PHP Settings
php_modules: [ 'php', 'php-curl', 'php-gd', 'php-mbstring', 'php-xml', 'php-xmlrpc', 'php-soap', 'php-intl', 'php-zip' ]
 
#MySQL Settings
mysql_root_password: "centos"
mysql_db: "wpdb"
mysql_user: "root"
mysql_password: "centos"
mysql_modules: [ 'mysql-server', 'php-mysqlnd', 'python3-PyMySQL' ]
 
#HTTP Settings
http_host: "wp.com"
http_conf: "wp.com.conf"
http_port: "80"